### ISSUE TITLE
Mac Customizations

### ISSUE THREAD

**Issue by therimalaya** [danielmai/.emacs.d#5] opened 2016-10-20 17:08 UTC
I liked the customization with mac. I can play with cmd key. But with those customization enable, I am not able to use `{` and `}` keys and also `[` and `[` key. Is there any way to use the `cmd` keybinding along with getting those brackets.

**Comment by danielmai** [comment] 2017-10-14 20:34
@therimalaya I'm not sure what the problem is here. In my set up, setting key bindings for "s-{" and "s-}" doesn't conflict with inserting "{", "}", "[", or "]". Are you still having this issue?

**Comment by danielmai** [comment] 2018-11-05 17:50
I'll close this issue but let me know if it's still a problem.

**Closed as completed by danielmai** 2018-11-05 17:50 UTC
